In [93]:
import numpy as np
print(np.__version__)

1.20.1


In [94]:
np_arry = np.array([1,4,2,5,3])
print(np_arry,type(np_arry),np_arry.dtype)

[1 4 2 5 3] <class 'numpy.ndarray'> int32


In [95]:
np_arry = np.array([1,4.13,2,5,3])
print(np_arry,type(np_arry),np_arry.dtype)

[1.   4.13 2.   5.   3.  ] <class 'numpy.ndarray'> float64


In [96]:
np_arry = np.array([1,4,2,5,3], dtype ='float32')
print(np_arry,type(np_arry),np_arry.dtype)

[1. 4. 2. 5. 3.] <class 'numpy.ndarray'> float32


In [97]:
np_arry = np.array([range(i,i+3)for i in [2,4,6]])
print(np_arry,type(np_arry),np_arry.dtype)

[[2 3 4]
 [4 5 6]
 [6 7 8]] <class 'numpy.ndarray'> int32


In [98]:
res = np.random.random()
print(res)

0.5813042122015738


In [99]:
res = np.random.random((1,))
print(res)

[0.98963407]


In [100]:
res=np.random.random((2,4,3))
print(res)

[[[0.0249832  0.27293016 0.68158807]
  [0.18265689 0.83840788 0.66489368]
  [0.37658252 0.68285431 0.6742609 ]
  [0.98389359 0.4587545  0.88576627]]

 [[0.28047296 0.12081633 0.49855919]
  [0.21096797 0.77738842 0.23149998]
  [0.12698706 0.70951765 0.63218177]
  [0.9642325  0.73589852 0.14428171]]]


In [101]:
res=np.random.random((3,3))
print(res)

[[0.52676673 0.78052834 0.74754352]
 [0.42070145 0.45251536 0.18944344]
 [0.16420884 0.46155101 0.09189356]]


In [102]:
res=np.random.rand(3,3)
print(res)

[[0.77948923 0.00461302 0.4578246 ]
 [0.93984597 0.64850662 0.41368602]
 [0.138237   0.04361324 0.82081032]]


In [103]:
res=np.random.randint(0,10,(3,3))
print(res)

[[6 4 0]
 [2 2 5]
 [2 5 4]]


In [104]:
res=np.random.normal(0,3,(3,3))
print(res)

[[-0.93999624 -2.53174977  3.18194677]
 [ 3.34588606  1.79701881 -5.05147503]
 [-0.08717597  4.36767611 -6.5961083 ]]
