In [1]:
import numpy as np

In [2]:
x=np.arange(10)
print(x)
print(x[:5])
print()

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]



In [3]:
x=np.arange(1,10)
print(x.shape)
print(x)
x1=x.reshape((3,3))
print(x1.shape)
print(x1)

(9,)
[1 2 3 4 5 6 7 8 9]
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
x1[2,2]=0
print(x1)

[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [5]:
x = np.array([1, 2, 3])
print(x.shape, x.ndim, '\n', x, '\n')

# 通过变形获得的行向量：x->x1
x1 = x.reshape((1, 3))
print(x1.shape, x1.ndim, '\n', x1, '\n')

# 通过变形获得的列向量：x1->x2
x2 = x.reshape((3, 1))
print(x2.shape, x2.ndim, '\n', x2, '\n')

(3,) 1 
 [1 2 3] 

(1, 3) 2 
 [[1 2 3]] 

(3, 1) 2 
 [[1]
 [2]
 [3]] 



In [6]:
x = np.random.randint(10, size=(3, 4))
print(x.shape, x.ndim, '\n', x, '\n')
x1 = np.reshape(x, (12,))
print(x1.shape, x1.ndim, '\n', x1, '\n')

(3, 4) 2 
 [[6 7 0 7]
 [7 1 3 6]
 [9 0 0 7]] 

(12,) 1 
 [6 7 0 7 7 1 3 6 9 0 0 7] 



In [7]:
x = np.random.randint(10, size=(3, 8))
print(x)

# 沿axis=1方向，在1、5索引位置处分裂
# 对返回的结果，通过赋值语句，将子数组进行解包操作。
x_split1, x_split2, x_split3 = np.split(x, [1, 5], axis=1)
print(x_split1, '\n\n', x_split2, '\n\n', x_split3)

[[1 5 9 4 8 6 0 3]
 [8 1 3 8 4 8 2 9]
 [5 3 1 4 6 0 4 9]]
[[1]
 [8]
 [5]] 

 [[5 9 4 8]
 [1 3 8 4]
 [3 1 4 6]] 

 [[6 0 3]
 [8 2 9]
 [0 4 9]]


In [8]:
grid = np.arange(16).reshape((4, 4))
print(grid)
print('----------')

upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)
print('----------')

left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
----------
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [9]:
import numpy as np
np.random.seed(0)

# 定义数组元素求倒数的函数
def compute_reciprocals(values):
   output = np.empty(len(values))
   for i in range(len(values)):
       output[i] = 1.0 / values[i]
   return output


values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [10]:
# 运算代码时，速度会很慢，请耐性等待。
# 左边的In[*]，*代表程序后台繁忙运行。
big_array = np.random.randint(1, 100, size=100000)
# 使用%timeit魔法函数测试规模是100000的数组元素求逆操作。
%timeit compute_reciprocals(big_array)

199 ms ± 7.33 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
# 运算代码时，速度会很慢，请耐性等待。
# 左边的In[*]，*代表程序后台繁忙运行。
big_array = np.random.randint(1, 100, size=100000)
# 使用%timeit魔法函数测试规模是100000的数组元素求逆操作。
%timeit compute_reciprocals(big_array)

205 ms ± 15.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
