In [2]:
import numpy as np

In [8]:
x=np.arange(10)
print(x)
print(x[:5])
print()

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [27]:
x=np.arange(1,10)
print(x.shape)
print(x)
x1=x.reshape((3,3))
print(x1.shape)
print(x1)

(9,)
[1 2 3 4 5 6 7 8 9]
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
x1[2,2]=0
print(x1)

[[1 2 3]
 [4 5 6]
 [7 8 0]]
